data:
  train: "ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData"
#  train: "data_select/train"
  valid: "ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData"
  test: "ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData"
#  concat: "plane"
  concat: "channels"
#  test: "data_select/test"
train:
  batch_size: 1
  step_slice: 32
#  step_slice: 2
  slice_deep: 96
#  slice_deep: 4
  slice_size: 192

  init_method: "xavier"
  optimizer: "Adam"
  scheduler: 'exp_lr'
  learning_rate: 2e-4
  epochs: 150
  device: cuda:0

  pretrain: False
  model: "UNet"

  ckpt: "result/models/UNet/1000-05-22-08-17-05/best_model_epoch_5.ckpt"
  result_dir: "result/models/"

test:
  batch_size: 1
  step_slice: 32

  slice_deep: 96
  slice_size: 192
  model: "UNet"
  device: cuda:0
  ckpt: "result/models/UNet/1111-05-31-17-33-11/best_model_epoch_28.ckpt"
  result_dir: "result/models/"

mask:
  # 1, 2, 3, 6, 8, 12,
  mask_kernel_size: 12
  train_binary_mask: "1111"
  test_binary_mask: "1000"
  train_mask_rate: 0.75
  test_mask_rate: 1

loss:
  mask_rate: 0.8