data:
  train_dir: "E:\Work\dataset\ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData"
  test_dir: "E:\Work\dataset\ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData"
train:
  batch_size: 32
  learning_rate: 1e-3
  epochs: 120
  device: cuda
  load_dir: "result/models/UNet/1000-05-17-22-21-24/"
  pretrain: False
  model: "UNet"
  model_save_dir: "result/models/"
  optimizer: "Adam"

  lr_scheduler: "CosineAnnealingWarmRestart"


evaluations: {dice, ssim}

test:

loss:
  mask_rate: 0.8



mask:
  mask_kernel_size: 12
  single_image_size: 192
  train_binary_mask: 1111
  test_binary_mask: 1111
  mask_rate: 0.5