data:
  train: "data/raw/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData"
  valid:
  test: "data/raw/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData"
train:
  batch_size: 1
  step_slice: 16

  slice_deep: 128
  slice_size: 192

  init_method: "xavier"
  scheduler: 'cosine_wr'
  learning_rate: 1e-3
  epochs: 120
  device: cuda:0

  pretrain: False
  model: "UNet"

  ckpt: "result/models/UNet/1000-05-17-22-21-24/"
  result_dir: "result/models/"

mask:
  mask_kernel_size: 3
  train_binary_mask: "1000"
  test_binary_mask: "1000"
  train_mask_rate: 0.75
  test_mask_rate: 1

loss:
  mask_rate: 0.8