data:
  train: "data_raw/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData"
#  train: "data_select/train"
  valid:
  test: "data_raw/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData"
#  test: "data_select/test"
train:
  batch_size: 1
  step_slice: 16
#  step_slice: 2
  slice_deep: 128
#  slice_deep: 4
  slice_size: 192

  init_method: "xavier"
  optimizer: "Adam"
  scheduler: 'cosine_wr'
  learning_rate: 1e-3
  epochs: 120
  device: cuda:0

  pretrain: True
  model: "UNet"

  ckpt: "result/models/UNet/1000-05-22-08-17-05/best_model_epoch_5.ckpt"
  result_dir: "result/models/"

test:
  batch_size: 1
  step_slice: 16

  slice_deep: 128
  slice_size: 192
  model: "UNet"
  device: cuda:0
  ckpt: "result/models/UNet/1000-05-22-08-17-05/best_model_epoch_5.ckpt"
  result_dir: "result/models/"

mask:
  mask_kernel_size: 3
  train_binary_mask: "1000"
  test_binary_mask: "1000"
  train_mask_rate: 0.75
  test_mask_rate: 0.95

loss:
  mask_rate: 0.8